// Code generated by sqlc. DO NOT EDIT.
// source: queries/api_keys.sql

package db

import (
	"context"
	"time"
)

const getAPIKey = `SELECT key_hash, name, role, created_at FROM api_keys WHERE key_hash = $1`

func (q *Queries) GetAPIKey(ctx context.Context, keyHash string) (APIKey, error) {
	row := q.db.QueryRow(ctx, getAPIKey, keyHash)
	var i APIKey
	err := row.Scan(&i.KeyHash, &i.Name, &i.Role, &i.CreatedAt)
	return i, err
}

const getAPIKeyByName = `SELECT key_hash, name, role, created_at FROM api_keys WHERE name = $1`

func (q *Queries) GetAPIKeyByName(ctx context.Context, name string) (APIKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByName, name)
	var i APIKey
	err := row.Scan(&i.KeyHash, &i.Name, &i.Role, &i.CreatedAt)
	return i, err
}

const listAPIKeys = `SELECT key_hash, name, role, created_at FROM api_keys ORDER BY created_at`

func (q *Queries) ListAPIKeys(ctx context.Context) ([]APIKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKey
	for rows.Next() {
		var i APIKey
		if err := rows.Scan(&i.KeyHash, &i.Name, &i.Role, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

type CreateAPIKeyParams struct {
	KeyHash string `json:"key_hash"`
	Name    string `json:"name"`
	Role    string `json:"role"`
}

const createAPIKey = `INSERT INTO api_keys (key_hash, name, role)
VALUES ($1, $2, $3)
RETURNING key_hash, name, role, created_at`

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey, arg.KeyHash, arg.Name, arg.Role)
	var i APIKey
	err := row.Scan(&i.KeyHash, &i.Name, &i.Role, &i.CreatedAt)
	return i, err
}

const deleteAPIKeyByName = `DELETE FROM api_keys WHERE name = $1`

func (q *Queries) DeleteAPIKeyByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteAPIKeyByName, name)
	return err
}

// CountAPIKeys returns the total number of API keys (used for bootstrap logic).
func (q *Queries) CountAPIKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, `SELECT COUNT(*) FROM api_keys`)
	var n int64
	return n, row.Scan(&n)
}

// Stub: pgx returns this sentinel on no-rows.
// Callers should compare errors.Is(err, pgx.ErrNoRows).
var _ = time.Time{}
