// Code generated by sqlc. DO NOT EDIT.
// source: queries/deployments.sql

package db

import "context"

const depCols = `id, active, count, image_ids, network_ids, ipam, ttl_minutes`

func scanDeployment(r interface{ Scan(...any) error }, d *Deployment) error {
	return r.Scan(&d.ID, &d.Active, &d.Count, &d.ImageIds, &d.NetworkIds, &d.Ipam, &d.TtlMinutes)
}

const listDeployments = `SELECT ` + depCols + ` FROM deployments ORDER BY id`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.Query(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := scanDeployment(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getDeployment = `SELECT ` + depCols + ` FROM deployments WHERE id = $1`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i Deployment
	err := scanDeployment(row, &i)
	return i, err
}

type CreateDeploymentParams struct {
	ID         string   `json:"id"`
	Active     bool     `json:"active"`
	Count      int32    `json:"count"`
	ImageIds   []string `json:"image_ids"`
	NetworkIds []string `json:"network_ids"`
	Ipam       string   `json:"ipam"`
	TtlMinutes int32    `json:"ttl_minutes"`
}

const createDeployment = `INSERT INTO deployments (id, active, count, image_ids, network_ids, ipam, ttl_minutes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING ` + depCols

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment,
		arg.ID, arg.Active, arg.Count, arg.ImageIds, arg.NetworkIds, arg.Ipam, arg.TtlMinutes)
	var i Deployment
	err := scanDeployment(row, &i)
	return i, err
}

type UpdateDeploymentParams struct {
	ID         string   `json:"id"`
	Active     bool     `json:"active"`
	Count      int32    `json:"count"`
	ImageIds   []string `json:"image_ids"`
	NetworkIds []string `json:"network_ids"`
	Ipam       string   `json:"ipam"`
	TtlMinutes int32    `json:"ttl_minutes"`
}

const updateDeployment = `UPDATE deployments
SET active = $2, count = $3, image_ids = $4, network_ids = $5, ipam = $6, ttl_minutes = $7
WHERE id = $1
RETURNING ` + depCols

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, updateDeployment,
		arg.ID, arg.Active, arg.Count, arg.ImageIds, arg.NetworkIds, arg.Ipam, arg.TtlMinutes)
	var i Deployment
	err := scanDeployment(row, &i)
	return i, err
}

const deleteDeployment = `DELETE FROM deployments WHERE id = $1`

func (q *Queries) DeleteDeployment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDeployment, id)
	return err
}
