// Code generated by sqlc. DO NOT EDIT.
// source: queries/events.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

type CreateEventParams struct {
	PotID   string          `json:"pot_id"`
	Time    time.Time       `json:"time"`
	Service string          `json:"service"`
	Kind    string          `json:"kind"`
	Source  string          `json:"source"`
	Data    json.RawMessage `json:"data"`
}

const createEvent = `INSERT INTO events (pot_id, time, service, kind, source, data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, pot_id, time, service, kind, source, data`

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.PotID, arg.Time, arg.Service, arg.Kind, arg.Source, arg.Data)
	var i Event
	err := row.Scan(&i.ID, &i.PotID, &i.Time, &i.Service, &i.Kind, &i.Source, &i.Data)
	return i, err
}

const listRecentEvents = `SELECT id, pot_id, time, service, kind, source, data FROM events ORDER BY time DESC LIMIT $1`

func (q *Queries) ListRecentEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(&i.ID, &i.PotID, &i.Time, &i.Service, &i.Kind, &i.Source, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listEventsByPot = `SELECT id, pot_id, time, service, kind, source, data FROM events WHERE pot_id = $1 ORDER BY time DESC LIMIT $2`

func (q *Queries) ListEventsByPot(ctx context.Context, potID string, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByPot, potID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(&i.ID, &i.PotID, &i.Time, &i.Service, &i.Kind, &i.Source, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}
