// Code generated by sqlc. DO NOT EDIT.
// source: queries/host.sql

package db

import "context"

const getHost = `SELECT id, network, mode, static_ip, static_gateway, static_dns FROM network_host WHERE id = 1`

func (q *Queries) GetHost(ctx context.Context) (NetworkHost, error) {
	row := q.db.QueryRow(ctx, getHost)
	var i NetworkHost
	err := row.Scan(&i.ID, &i.Network, &i.Mode, &i.StaticIp, &i.StaticGateway, &i.StaticDns)
	return i, err
}

type UpsertHostParams struct {
	Network       string `json:"network"`
	Mode          string `json:"mode"`
	StaticIp      string `json:"static_ip"`
	StaticGateway string `json:"static_gateway"`
	StaticDns     string `json:"static_dns"`
}

const upsertHost = `INSERT INTO network_host (id, network, mode, static_ip, static_gateway, static_dns)
VALUES (1, $1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    network        = EXCLUDED.network,
    mode           = EXCLUDED.mode,
    static_ip      = EXCLUDED.static_ip,
    static_gateway = EXCLUDED.static_gateway,
    static_dns     = EXCLUDED.static_dns`

func (q *Queries) UpsertHost(ctx context.Context, arg UpsertHostParams) error {
	_, err := q.db.Exec(ctx, upsertHost, arg.Network, arg.Mode, arg.StaticIp, arg.StaticGateway, arg.StaticDns)
	return err
}
