// Code generated by sqlc. DO NOT EDIT.
// source: queries/images.sql

package db

import (
	"context"
	"encoding/json"
)

const listImages = `SELECT id, base, version, os, features FROM images ORDER BY id`

func (q *Queries) ListImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, listImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.ID, &i.Base, &i.Version, &i.Os, &i.Features); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getImage = `SELECT id, base, version, os, features FROM images WHERE id = $1`

func (q *Queries) GetImage(ctx context.Context, id string) (Image, error) {
	row := q.db.QueryRow(ctx, getImage, id)
	var i Image
	err := row.Scan(&i.ID, &i.Base, &i.Version, &i.Os, &i.Features)
	return i, err
}

type UpsertImageParams struct {
	ID       string          `json:"id"`
	Base     string          `json:"base"`
	Version  string          `json:"version"`
	Os       string          `json:"os"`
	Features json.RawMessage `json:"features"`
}

const upsertImage = `INSERT INTO images (id, base, version, os, features)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    base     = EXCLUDED.base,
    version  = EXCLUDED.version,
    os       = EXCLUDED.os,
    features = EXCLUDED.features
RETURNING id, base, version, os, features`

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, upsertImage, arg.ID, arg.Base, arg.Version, arg.Os, arg.Features)
	var i Image
	err := row.Scan(&i.ID, &i.Base, &i.Version, &i.Os, &i.Features)
	return i, err
}
