// Code generated by sqlc. DO NOT EDIT.
// source: queries/interfaces.sql

package db

import "context"

const listInterfaces = `SELECT id, enabled, link, mode, aggregate_group FROM interfaces ORDER BY id`

func (q *Queries) ListInterfaces(ctx context.Context) ([]Interface, error) {
	rows, err := q.db.Query(ctx, listInterfaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Interface
	for rows.Next() {
		var i Interface
		if err := rows.Scan(&i.ID, &i.Enabled, &i.Link, &i.Mode, &i.AggregateGroup); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getInterface = `SELECT id, enabled, link, mode, aggregate_group FROM interfaces WHERE id = $1`

func (q *Queries) GetInterface(ctx context.Context, id string) (Interface, error) {
	row := q.db.QueryRow(ctx, getInterface, id)
	var i Interface
	err := row.Scan(&i.ID, &i.Enabled, &i.Link, &i.Mode, &i.AggregateGroup)
	return i, err
}

type UpsertInterfaceParams struct {
	ID             string `json:"id"`
	Enabled        bool   `json:"enabled"`
	Link           bool   `json:"link"`
	Mode           string `json:"mode"`
	AggregateGroup string `json:"aggregate_group"`
}

const upsertInterface = `INSERT INTO interfaces (id, enabled, link, mode, aggregate_group)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    enabled         = EXCLUDED.enabled,
    link            = EXCLUDED.link,
    mode            = EXCLUDED.mode,
    aggregate_group = EXCLUDED.aggregate_group`

func (q *Queries) UpsertInterface(ctx context.Context, arg UpsertInterfaceParams) error {
	_, err := q.db.Exec(ctx, upsertInterface, arg.ID, arg.Enabled, arg.Link, arg.Mode, arg.AggregateGroup)
	return err
}
