// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: schema.sql

package db

import (
	"encoding/json"
	"time"
)

type Pot struct {
	ID            string     `json:"id"`
	DeploymentID  string     `json:"deployment_id"`
	ImageID       string     `json:"image_id"`
	NetworkID     string     `json:"network_id"`
	Discriminator int32      `json:"discriminator"`
	Status        string     `json:"status"`
	Ip            string     `json:"ip"`
	CreatedAt     time.Time  `json:"created_at"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CredHint      string     `json:"cred_hint"`
	Mac           string     `json:"mac"`
}

type Deployment struct {
	ID         string   `json:"id"`
	Active     bool     `json:"active"`
	Count      int32    `json:"count"`
	ImageIds   []string `json:"image_ids"`
	NetworkIds []string `json:"network_ids"`
	Ipam       string   `json:"ipam"`
	TtlMinutes int32    `json:"ttl_minutes"`
}

type Image struct {
	ID       string          `json:"id"`
	Base     string          `json:"base"`
	Version  string          `json:"version"`
	Os       string          `json:"os"`
	Features json.RawMessage `json:"features"`
}

type Interface struct {
	ID             string `json:"id"`
	Enabled        bool   `json:"enabled"`
	Link           bool   `json:"link"`
	Mode           string `json:"mode"`
	AggregateGroup string `json:"aggregate_group"`
}

type Network struct {
	ID          string `json:"id"`
	Enabled     bool   `json:"enabled"`
	InterfaceID string `json:"interface_id"`
	Type        string `json:"type"`
	VlanID      int32  `json:"vlan_id"`
	Subnet      string `json:"subnet"`
}

type NetworkHost struct {
	ID            int32  `json:"id"`
	Network       string `json:"network"`
	Mode          string `json:"mode"`
	StaticIp      string `json:"static_ip"`
	StaticGateway string `json:"static_gateway"`
	StaticDns     string `json:"static_dns"`
}

type APIKey struct {
	KeyHash   string    `json:"key_hash"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Event struct {
	ID      int64           `json:"id"`
	PotID   string          `json:"pot_id"`
	Time    time.Time       `json:"time"`
	Service string          `json:"service"`
	Kind    string          `json:"kind"`
	Source  string          `json:"source"`
	Data    json.RawMessage `json:"data"`
}
