// Code generated by sqlc. DO NOT EDIT.
// source: queries/networks.sql

package db

import "context"

const listNetworks = `SELECT id, enabled, interface_id, type, vlan_id, subnet FROM networks ORDER BY id`

func (q *Queries) ListNetworks(ctx context.Context) ([]Network, error) {
	rows, err := q.db.Query(ctx, listNetworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Network
	for rows.Next() {
		var i Network
		if err := rows.Scan(&i.ID, &i.Enabled, &i.InterfaceID, &i.Type, &i.VlanID, &i.Subnet); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getNetwork = `SELECT id, enabled, interface_id, type, vlan_id, subnet FROM networks WHERE id = $1`

func (q *Queries) GetNetwork(ctx context.Context, id string) (Network, error) {
	row := q.db.QueryRow(ctx, getNetwork, id)
	var i Network
	err := row.Scan(&i.ID, &i.Enabled, &i.InterfaceID, &i.Type, &i.VlanID, &i.Subnet)
	return i, err
}

type CreateNetworkParams struct {
	ID          string `json:"id"`
	Enabled     bool   `json:"enabled"`
	InterfaceID string `json:"interface_id"`
	Type        string `json:"type"`
	VlanID      int32  `json:"vlan_id"`
	Subnet      string `json:"subnet"`
}

const createNetwork = `INSERT INTO networks (id, enabled, interface_id, type, vlan_id, subnet)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, enabled, interface_id, type, vlan_id, subnet`

func (q *Queries) CreateNetwork(ctx context.Context, arg CreateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, createNetwork,
		arg.ID, arg.Enabled, arg.InterfaceID, arg.Type, arg.VlanID, arg.Subnet)
	var i Network
	err := row.Scan(&i.ID, &i.Enabled, &i.InterfaceID, &i.Type, &i.VlanID, &i.Subnet)
	return i, err
}

type UpdateNetworkParams struct {
	ID          string `json:"id"`
	Enabled     bool   `json:"enabled"`
	InterfaceID string `json:"interface_id"`
	Type        string `json:"type"`
	VlanID      int32  `json:"vlan_id"`
	Subnet      string `json:"subnet"`
}

const updateNetwork = `UPDATE networks
SET enabled = $2, interface_id = $3, type = $4, vlan_id = $5, subnet = $6
WHERE id = $1
RETURNING id, enabled, interface_id, type, vlan_id, subnet`

func (q *Queries) UpdateNetwork(ctx context.Context, arg UpdateNetworkParams) (Network, error) {
	row := q.db.QueryRow(ctx, updateNetwork,
		arg.ID, arg.Enabled, arg.InterfaceID, arg.Type, arg.VlanID, arg.Subnet)
	var i Network
	err := row.Scan(&i.ID, &i.Enabled, &i.InterfaceID, &i.Type, &i.VlanID, &i.Subnet)
	return i, err
}

const deleteNetwork = `DELETE FROM networks WHERE id = $1`

func (q *Queries) DeleteNetwork(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNetwork, id)
	return err
}
