// Code generated by sqlc. DO NOT EDIT.
// source: queries/pots.sql

package db

import (
	"context"
	"time"
)

const potCols = `id, deployment_id, image_id, network_id, discriminator, status, ip, created_at, expires_at, cred_hint, mac`

func scanPot(r interface{ Scan(...any) error }, p *Pot) error {
	return r.Scan(&p.ID, &p.DeploymentID, &p.ImageID, &p.NetworkID,
		&p.Discriminator, &p.Status, &p.Ip, &p.CreatedAt, &p.ExpiresAt, &p.CredHint, &p.Mac)
}

const listPots = `SELECT ` + potCols + ` FROM pots ORDER BY created_at`

func (q *Queries) ListPots(ctx context.Context) ([]Pot, error) {
	rows, err := q.db.Query(ctx, listPots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pot
	for rows.Next() {
		var i Pot
		if err := scanPot(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listPotsByDeployment = `SELECT ` + potCols + ` FROM pots WHERE deployment_id = $1 ORDER BY created_at`

func (q *Queries) ListPotsByDeployment(ctx context.Context, deploymentID string) ([]Pot, error) {
	rows, err := q.db.Query(ctx, listPotsByDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pot
	for rows.Next() {
		var i Pot
		if err := scanPot(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listExpiredPots = `SELECT ` + potCols + ` FROM pots WHERE expires_at IS NOT NULL AND expires_at <= NOW()`

func (q *Queries) ListExpiredPots(ctx context.Context) ([]Pot, error) {
	rows, err := q.db.Query(ctx, listExpiredPots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pot
	for rows.Next() {
		var i Pot
		if err := scanPot(rows, &i); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const getPot = `SELECT ` + potCols + ` FROM pots WHERE id = $1`

func (q *Queries) GetPot(ctx context.Context, id string) (Pot, error) {
	row := q.db.QueryRow(ctx, getPot, id)
	var i Pot
	err := scanPot(row, &i)
	return i, err
}

type CreatePotParams struct {
	ID            string     `json:"id"`
	DeploymentID  string     `json:"deployment_id"`
	ImageID       string     `json:"image_id"`
	NetworkID     string     `json:"network_id"`
	Discriminator int32      `json:"discriminator"`
	Status        string     `json:"status"`
	Ip            string     `json:"ip"`
	ExpiresAt     *time.Time `json:"expires_at"`
	CredHint      string     `json:"cred_hint"`
	Mac           string     `json:"mac"`
}

const createPot = `INSERT INTO pots (id, deployment_id, image_id, network_id, discriminator, status, ip, expires_at, cred_hint, mac)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING ` + potCols

func (q *Queries) CreatePot(ctx context.Context, arg CreatePotParams) (Pot, error) {
	row := q.db.QueryRow(ctx, createPot, arg.ID, arg.DeploymentID, arg.ImageID,
		arg.NetworkID, arg.Discriminator, arg.Status, arg.Ip, arg.ExpiresAt, arg.CredHint, arg.Mac)
	var i Pot
	err := scanPot(row, &i)
	return i, err
}

type UpdatePotStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

const updatePotStatus = `UPDATE pots SET status = $2 WHERE id = $1`

func (q *Queries) UpdatePotStatus(ctx context.Context, arg UpdatePotStatusParams) error {
	_, err := q.db.Exec(ctx, updatePotStatus, arg.ID, arg.Status)
	return err
}

type UpdatePotIPParams struct {
	ID string `json:"id"`
	Ip string `json:"ip"`
}

const updatePotIP = `UPDATE pots SET ip = $2 WHERE id = $1`

func (q *Queries) UpdatePotIP(ctx context.Context, arg UpdatePotIPParams) error {
	_, err := q.db.Exec(ctx, updatePotIP, arg.ID, arg.Ip)
	return err
}

const deletePot = `DELETE FROM pots WHERE id = $1`

func (q *Queries) DeletePot(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePot, id)
	return err
}

type MaxDiscriminatorParams struct {
	DeploymentID string `json:"deployment_id"`
	NetworkID    string `json:"network_id"`
	ImageID      string `json:"image_id"`
}

const maxDiscriminator = `SELECT COALESCE(MAX(discriminator), 0)::integer AS max_disc
FROM pots
WHERE deployment_id = $1 AND network_id = $2 AND image_id = $3`

func (q *Queries) MaxDiscriminator(ctx context.Context, arg MaxDiscriminatorParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxDiscriminator, arg.DeploymentID, arg.NetworkID, arg.ImageID)
	var maxDisc int32
	err := row.Scan(&maxDisc)
	return maxDisc, err
}
